-- CreateTable
CREATE TABLE "Device" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "systemPort" INTEGER NOT NULL,
    "host" TEXT NOT NULL,
    "proxyPort" INTEGER,
    "proxyHost" TEXT,
    "wdaLocalPort" INTEGER,
    "name" TEXT NOT NULL,
    "udid" TEXT NOT NULL,
    "state" TEXT NOT NULL,
    "sdk" TEXT NOT NULL,
    "platform" TEXT NOT NULL,
    "deviceType" TEXT NOT NULL,
    "busy" BOOLEAN NOT NULL DEFAULT false,
    "userBlocked" BOOLEAN NOT NULL DEFAULT false,
    "realDevice" BOOLEAN NOT NULL,
    "session_id" TEXT,
    "offline" BOOLEAN NOT NULL DEFAULT false,
    "mjpegServerPort" INTEGER,
    "lastCmdExecutedAt" BIGINT,
    "totalUtilizationTimeMilliSec" BIGINT NOT NULL DEFAULT 0,
    "sessionStartTime" BIGINT NOT NULL DEFAULT 0,
    "newCommandTimeout" INTEGER,
    "cloud" TEXT,
    "derivedDataPath" TEXT,
    "chromeDriverPath" TEXT,
    "capability" TEXT,
    "adbRemoteHost" TEXT NOT NULL,
    "adbPort" INTEGER NOT NULL,
    "nodeId" TEXT,
    "width" TEXT NOT NULL,
    "height" TEXT NOT NULL,
    "liveStreaming" BOOLEAN,
    "wdaBundleId" TEXT,
    "productModel" TEXT,
    "deviceTypeIdentifier" TEXT,
    "proxyUrl" TEXT,
    "proxySessionId" TEXT,
    "prebuiltWDAPath" TEXT,
    "tags" TEXT,
    "webDriverAgentUrl" TEXT,
    "webDriverAgentHost" TEXT,
    "sessionResponse" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

-- CreateIndex
CREATE UNIQUE INDEX "Device_host_udid_key" ON "Device"("host", "udid");
