name: Test on Android and iOS

on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set up Node JS
        uses: actions/setup-node@v1
        with:
          node-version: "16.7.0"
      - name: Clean Packages
        run: |
          npm ci
          npm test